language: python
cache: pip
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install pipenv --upgrade
- pipenv install --dev
script:
- pipenv run -- pytest --cov=hendrix -v test
after_success:
  - codecov
