language: python
cache: pip
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install pipenv --upgrade
- pipenv install --dev
script:
- pipenv run pipenv run "pytest --cov=hendrix -v test"
- codecov
after_success:
  - codecov
